name: Auto Star

on:
  push:
    branches:
      - main

jobs:
  auto_star:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Star repository
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        node .github/workflows/star-repository.js
